import "./globals.css";
import type { Metadata } from "next";

import logoImageHeader from "../../public/icon.png";
import Head from "next/head";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Debb Downloader",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <Image src={logoImageHeader} alt="logo" />
      </Head>
      <body>{children}</body>
    </html>
  );
}
